export const SET_MENU_SUCCESS = "SET_MENU_SUCCESS";
export const FETCH_MENU_FAILED = "FETCH_MENU_FAILED"

export const LOGIN_AUTH_START = "LOGIN_AUTH_START"
export const LOGIN_AUTH_SUCCESS = "LOGIN_AUTH_SUCCESS"
export const LOGIN_AUTH_FAILED = "LOGIN_AUTH_FAILED"
export const LOGIN_AUTH_LOGOUT = "LOGIN_AUTH_LOGOUT"

export const SIGNUP_AUTH_START = "SIGNUP_AUTH_START"
export const SIGNUP_AUTH_SUCCESS = "SIGNUP_AUTH_SUCCESS" 
export const SIGNUP_AUTH_FAILED = "SIGNUP_AUTH_FAILED"
export const SIGNUP_AUTH_LOGOUT = "SIGNUP_AUTH_LOGOUT"

export const FETCH_ORDERS_START = "FETCH_ORDERS_START"
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS"
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED"
