export const SET_MENU_SUCCESS = "SET_MENU_SUCCESS";
export const FETCH_MENU_FAILED = "FETCH_MENU_FAILED"

export const LOGIN_AUTH_START = "LOGIN_AUTH_START"
export const LOGIN_AUTH_SUCCESS = "LOGIN_AUTH_SUCCESS"
export const LOGIN_AUTH_FAILED = "LOGIN_AUTH_FAILED"